name: Artifacts Demo
on: 
    push:
        branches: 
            - main
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Check code
              uses: actions/checkout@v3
            - name: install dependencies
              run : npm install
            - name: run lint
              run : npm run lint
            - name: run test
              run : npm run test
            - name: run build
              run : npm run build
            - name: upload Artifacts # name of the artifacts
              uses: actions/upload-artifact@v3  #this action is for uploading the artifacts
              with:
                name: dist-files #name of file for storing
                path: dist       #Storing the files in these path

            - name: deploy code
              run : echo "deploying...."